[package]
name = "softfido"
version = "0.1.0"
authors = ["Helmut Eller <eller.helmut@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packed_struct = "0.3"
packed_struct_codegen = "0.3"
# bitflags = "1.1.0"
rand = "0.7.0"

[build-dependencies]
bindgen = "0.51"
